query CategoryProducts {
	products_categories_by_pk(id: 25) {
		products {
			title
			selling_price
		}
		name
		title
		coating_material
		description
		description_short
		image
		title_tag
		title_og
		parent_id
		meta_description
		keywords
		image_og
		description_og
		products_categories_files {
			directus_file {
				filename_disk
			}
		}
	}
}
